[package]
name = "tushare-derive"
version = "1.1.0"
edition = "2024"
license = "MIT"
description = "Procedural macros for tushare-api"
authors = ["rock huang <manj22@163.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
